# Generated by Django 5.0 on 2025-11-18 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('E', 'Efectivo'), ('D', 'Débito'), ('C', 'Crédito'), ('T', 'Transferencia'), ('P', 'PayPal')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('ultimo_acceso', models.DateField()),
                ('estado', models.BooleanField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=9)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=150)),
                ('estrellas', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkmaniaApp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('S', 'Simple'), ('D', 'Doble'), ('SU', 'Suite'), ('F', 'Familiar')], max_length=2)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupada'), ('M', 'Mantenimiento'), ('R', 'Reservada')], default='D', max_length=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='talkmaniaApp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='talkmaniaApp.cliente')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='talkmaniaApp.hotel')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkmaniaApp.tipo_pago')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkmaniaApp.habitacion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='talkmaniaApp.reserva')),
            ],
            options={
                'unique_together': {('reserva', 'habitacion')},
            },
        ),
    ]
